apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: db-credentials
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: db-credentials
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
